/* tslint:disable */
/* eslint-disable */
/**
 * Sage Recruitment
 * Simple List API with Nest.js
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClearListDTO
 */
export interface ClearListDTO {
    /**
     * 
     * @type {string}
     * @memberof ClearListDTO
     */
    listId: string;
}

export function ClearListDTOFromJSON(json: any): ClearListDTO {
    return ClearListDTOFromJSONTyped(json, false);
}

export function ClearListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClearListDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listId': json['listId'],
    };
}

export function ClearListDTOToJSON(value?: ClearListDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listId': value.listId,
    };
}


