/* tslint:disable */
/* eslint-disable */
/**
 * Sage Recruitment
 * Simple List API with Nest.js
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ReorderItem,
    ReorderItemFromJSON,
    ReorderItemFromJSONTyped,
    ReorderItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface ReorderListDTO
 */
export interface ReorderListDTO {
    /**
     * 
     * @type {number}
     * @memberof ReorderListDTO
     */
    listId: number;
    /**
     * 
     * @type {Array<ReorderItem>}
     * @memberof ReorderListDTO
     */
    items: Array<ReorderItem>;
}

export function ReorderListDTOFromJSON(json: any): ReorderListDTO {
    return ReorderListDTOFromJSONTyped(json, false);
}

export function ReorderListDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReorderListDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listId': json['listId'],
        'items': ((json['items'] as Array<any>).map(ReorderItemFromJSON)),
    };
}

export function ReorderListDTOToJSON(value?: ReorderListDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listId': value.listId,
        'items': ((value.items as Array<any>).map(ReorderItemToJSON)),
    };
}


