version: '3.3'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  backend:
    build: ./sage-server
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
  frontend:
    build: ./SageNext
    ports:
      - "3500:3000"
    depends_on:
      - "postgres"
      - "backend"
    environment:
      BACKEND: 'http://backend:3000'
      HOST: 'http://localhost:3000'


volumes:
  db_data:
