/* tslint:disable */
/* eslint-disable */
/**
 * Sage Recruitment
 * Simple List API with Nest.js
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ListItemEntity,
    ListItemEntityFromJSON,
    ListItemEntityFromJSONTyped,
    ListItemEntityToJSON,
} from './';

/**
 * 
 * @export
 * @interface ListEntity
 */
export interface ListEntity {
    /**
     * 
     * @type {string}
     * @memberof ListEntity
     */
    id: string;
    /**
     * 
     * @type {Array<ListItemEntity>}
     * @memberof ListEntity
     */
    items: Array<ListItemEntity>;
}

export function ListEntityFromJSON(json: any): ListEntity {
    return ListEntityFromJSONTyped(json, false);
}

export function ListEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'items': ((json['items'] as Array<any>).map(ListItemEntityFromJSON)),
    };
}

export function ListEntityToJSON(value?: ListEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'items': ((value.items as Array<any>).map(ListItemEntityToJSON)),
    };
}


