/* tslint:disable */
/* eslint-disable */
/**
 * Sage Recruitment
 * Simple List API with Nest.js
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveItemDTO
 */
export interface RemoveItemDTO {
    /**
     * 
     * @type {string}
     * @memberof RemoveItemDTO
     */
    itemId: string;
}

export function RemoveItemDTOFromJSON(json: any): RemoveItemDTO {
    return RemoveItemDTOFromJSONTyped(json, false);
}

export function RemoveItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveItemDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
    };
}

export function RemoveItemDTOToJSON(value?: RemoveItemDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'itemId': value.itemId,
    };
}


